export enum TokenEnum {
  ACCESS_SECRET = 'ACCESS_SECRET',
  REFRESH_SECRET = 'REFRESH_SECRET',
  EMAIL_CONFIRMATION_SECRET = 'EMAIL_CONFIRMATION_SECRET',
  PASSWORD_RESET_SECRET = 'PASSWORD_RESET_SECRET',
}
